services:
  - type: web
    name: lolhub-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: APP_NAME
        value: LoLHub
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: lolhub-database
          property: host
      - key: DB_PORT
        fromDatabase:
          name: lolhub-database
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: lolhub-database
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: lolhub-database
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: lolhub-database
          property: password
    healthCheckPath: /api/v1

